'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Czekolada
    Public Property id_czekolada As Integer
    Public Property id_rodzaj As Integer
    Public Property id_orzech As Integer
    Public Property id_owoc As Integer
    Public Property id_rozmiar As Integer
    Public Property id_kakao As Integer

    Public Overridable Property Kakao As Kakao
    Public Overridable Property Orzech As Orzech
    Public Overridable Property Owoc As Owoc
    Public Overridable Property Rodzaj_czekolady As Rodzaj_czekolady
    Public Overridable Property Rozmiar_tabliczki As Rozmiar_tabliczki

End Class
